development:
  database: db/grunt_dev.sqlite3
  adapter: sqlite3
  pool: 5
  timeout: 5000
#default: &default
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000
#development:
#  <<: *default
#  database: db/grunt_dev.sqlite3
#production:
#  <<: *default
#  database: db/grunt_prod.sqlite3
